language: python
python:
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - cmake
      - x11-utils
      - libxkbcommon-x11-0
      - xvfb
      - herbstluftwm # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#xvfb-assertionerror-timeouterror-when-using-waituntil-waitexposed-and-ui-events
      - qt5-default
      - qttools5-dev-tools

services:
  - xvfb

install:
  - export DISPLAY=":99.0" QT_DEBUG_PLUGINS=1  # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html?highlight=travis#xvfb-assertionerror-timeouterror-when-using-waituntil-waitexposed-and-ui-events
  - pip install -U pytest pytest-cov coveralls pytest-qt
  - pip install -r requirements_pilot.txt
  - pip install -r requirements_terminal.txt
  - pip install -e .
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3

# command to run tests
before_script:
  - "herbstluftwm &"
  - sleep 1

script:
  pytest --cov=autopilot --cov-report ter-missing tests

